//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Rental = new HashSet<Rental>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string RegistrationNumber { get; set; }
        public string BodyNumber { get; set; }
        public string EngineNumber { get; set; }
        public int YearOfIssue { get; set; }
        public string Image { get; set; }
        public Nullable<int> CarPrice { get; set; }
        public int RentalDayPrice { get; set; }
        public Nullable<System.DateTime> DateOfLastMaintenance { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public bool ReturnMark { get; set; }
    
        public virtual CarBrands CarBrands { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rental { get; set; }
    }
}
