//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int ID { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int CarID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> Service1ID { get; set; }
        public Nullable<int> Service2ID { get; set; }
        public Nullable<int> Service3ID { get; set; }
        public int RentalPeriod { get; set; }
        public int RentalCost { get; set; }
        public int PaymentStamp { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual AdditionalServices AdditionalServices1 { get; set; }
        public virtual AdditionalServices AdditionalServices2 { get; set; }
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
